# -*- coding: utf-8 -*-
"""Dynamic Inventory Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XVjdGbngUkmvjde9HePN8GTMcvb_sn8W

Python Simulation of Incidence Model (2.1) from Neslin, van Heerde (2009), to create dataset according to the equations. (2.2 2.3, 2.4).
"""

import random
from numpy.random import normal
import numpy as np
import pandas as pd
import math

def DynamicInventory(H, W, gamma_0, gamma_2, gamma_3):
  d=[]
  for h in range(H):
    cons_h = random.randint(6,9)
    for t in range(W+1):
      if t==0:
        inv = normal(loc=15, scale=0.40, size=2)[1]  #Inventory is initialized to a random number
        q =normal(loc=30, scale=0.1, size=2)[1]      #Quantity is initialized to a random number 
        util = 0 
      if t>0:
        inv = inv + q - cons_h                    # Inventory in t = Inventory in t-1 + Quantity in t-1 + CONS_H
        util = gamma_0 + gamma_2*cons_h + gamma_3*inv
        #prob = 1/(1+np.exp(-util))
        q = random.randint(25,30)                  # Quantity in t period is random number between 9 and 15         
      d.append(
            {
              'Household': h+1,
              'Week': t,
              'Quantity':q,
              'Inventory':inv,
              'Consumption': cons_h,
              'Gamma 0':gamma_0,
              'Gamma 2':gamma_2,
              'Gamma_3':gamma_3,
              'Utility Incidence':util,
              'Probablity':round(1/(1+math.exp(-util)),2)
            }
        )
  return pd.DataFrame(d)

DynamicInventory(500, 104, 0, 0.4, -0.01)